---
restylers:
  - stylish-haskell
        - "**/*.hs"
        - "!src/Yesod/Paginator/Pages.hs"  # avoid DerivingStrategies
  - brittany:
      include:
        - "**/*.hs"
        - "!src/Yesod/Paginator/Pages.hs"  # avoid DerivingStrategies
