name: yesod-paginator
version: 1.1.2.0
synopsis: A pagination approach for yesod
description: Paginate a list showing a per-item widget and links to other pages
category: Web, Yesod
author: Patrick Brisbin <pbrisbin@gmail.com>
license: MIT
homepage: http://github.com/pbrisbin/yesod-paginator

dependencies:
  - base < 5

ghc-options: -Wall

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src
  dependencies:
    - blaze-markup
    - path-pieces
    - persistent
    - safe
    - text
    - transformers
    - uri-encode
    - yesod-core

executables:
  yesod-paginator-example:
    main: Main.hs
    source-dirs: example
    dependencies:
      - warp
      - yesod
      - yesod-paginator
    when:
      - condition: ! '!(flag(examples))'
        buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - QuickCheck
      - hspec
      - quickcheck-classes
      - yesod-core
      - yesod-paginator
      - yesod-test
  doctests:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest

flags:
  examples:
    description: Build the examples
    manual: false
    default: false
