---
name: yesod-paginator
version: 1.1.0.1
synopsis: A pagination approach for yesod
description: Paginate a list showing a per-item widget and links to other pages
category: Web, Yesod
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
license: BSD3
homepage: http://github.com/pbrisbin/yesod-paginator
git: git://github.com/pbrisbin/yesod-paginator.git

dependencies:
  - base > 4.8.0 && < 5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - blaze-markup
    - path-pieces
    - persistent >=2.5
    - safe
    - text >=0.11 && <2.0
    - transformers
    - uri-encode
    - yesod-core >=1.4
  default-extensions:
    - NoImplicitPrelude

executables:
  yesod-paginator-example:
    main: Main.hs
    source-dirs: example
    dependencies:
      - warp
      - yesod
      - yesod-paginator
    when:
      - condition: ! '!(flag(examples))'
        buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - QuickCheck
      - hspec
      - quickcheck-classes
      - yesod-core
      - yesod-paginator
      - yesod-test
  doctests:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest

flags:
  examples:
    description: Build the examples
    manual: false
    default: false
