version: 2.1

orbs:
  stack-build: pbrisbin/stack-build@1.0.0

jobs:
  build:
    executor: stack-build/ubuntu
    steps:
      - checkout
      - stack-build/setup:
          stack-arguments: --flag yesod-paginator:examples
      - stack-build/build:
          stack-arguments: --flag yesod-paginator:examples
