name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v1

      - id: stack
        uses: freckle/stack-action@v3
        with:
          stack-arguments: --flag yesod-paginator:examples --coverage

      - uses: freckle/weeder-action@v1
        with:
          weeder-version: 2.2.0

      - name: Reformat coverage
        run: |
          tix='${{ steps.stack.outputs.local-hpc-root }}/combined/all/all.tix'
          stack --no-terminal install --copy-compiler-tool hpc-lcov
          stack --no-terminal exec -- hpc-lcov --file "$tix"

      - uses: codecov/codecov-action@v2
        with:
          files: ./lcov.info

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
      - run: |
          curl -o .hlint.yaml https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - uses: rwe/actions-hlint-run@v2
        with:
          fail-on: warning
