name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml   # ghc-9.8
          - stack.yaml           # ghc-9.6
          - stack-lts-21.25.yaml # ghc-9.4
          - stack-lts-20.26.yaml # ghc-9.2
          - stack-lts-19.33.yaml # ghc-9.0
          - stack-lts-18.28.yaml # ghc-8.10
          - stack-lts-16.31.yaml # ghc-8.8
          - stack-lts-14.27.yaml # ghc-8.6
          - stack-lts-12.26.yaml # ghc-8.4
      fail-fast: false

    env:
      STACK_YAML: ${{ matrix.stack-yaml }}

    steps:
      - uses: actions/checkout@v4

      - id: stack
        uses: freckle/stack-action@v5
        with:
          stack-arguments: --coverage
          compiler-tools: hpc-lcov

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        name: Reformat coverage
        run: stack exec -- hpc-lcov --file '${{ steps.stack.outputs.local-hpc-root }}/combined/all/all.tix'

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./lcov.info

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        uses: freckle/weeder-action@v2
        with:
          ghc-version: ${{ steps.stack.outputs.compiler-version }}

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
