name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml   # ghc-9.2
          - stack.yaml           # ghc-9.0
          - stack-lts-18.28.yaml # ghc-8.10
          - stack-lts-16.31.yaml # ghc-8.8
          - stack-lts-14.27.yaml # ghc-8.6
          - stack-lts-12.26.yaml # ghc-8.4
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v1
        with:
          stack-yaml: ${{ matrix.stack-yaml }}

      - id: stack
        uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
          stack-arguments: --coverage

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        name: Reformat coverage
        run: |
          tix='${{ steps.stack.outputs.local-hpc-root }}/combined/all/all.tix'
          stack --resolver lts-18.28 --no-terminal install --copy-compiler-tool hpc-lcov
          stack --resolver lts-18.28 --no-terminal exec -- hpc-lcov --file "$tix"

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./lcov.info

      - if: ${{ matrix.stack-yaml == 'stack.yaml' }}
        uses: freckle/weeder-action@v1

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
      - run: |
          curl -o .hlint.yaml https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - uses: rwe/actions-hlint-run@v2
        with:
          fail-on: warning
